# -*- coding: utf-8 -*-
import os
from flask import current_app, Blueprint, render_template, flash
from flask.ext.login import login_required, current_user
from flask import request, url_for, redirect
from .forms import PostForm
from ..extensions import db
from .models import Post, Tag

post = Blueprint("post", __name__, url_prefix='/post',
                        static_folder="../static")


@post.route('/wish', methods=['GET', 'POST'])
@login_required
def postwish():
    form = PostForm()

    if form.validate_on_submit():
        if form.tags.data:
            tags = [Tag(tag=form.tags.data)]
        else:
            tags = []
        if form.expire_on.data:
            expire_on = form.expire_on.data
        else:
            expire_on = None

        post = Post(text=form.text.data, tags=tags, timestamp=get_current_time(),
        			effective_on=form.effective_on.data, expire_on=expire_on,
                    user_id=current_user.id)
        db.session.merge(post)
        db.session.commit()
        flash('Your post is now live!')
        return redirect(url_for('frontend.index'))
#    posts = g.user.followed_posts().paginate(page, POSTS_PER_PAGE, False)
    return render_template('post/wish.html', form=form)

@post.route('/offer', methods=['GET', 'POST'])
@login_required
def postoffer():
    form = PostForm()
    return render_template('post/offer.html', form=form)

@post.route('/<int:user_id>/avatar/<path:filename>')
@login_required
def upload(user_id, filename): #filename should be autogenerated
    dir_path = os.path.join(current_app.config['UPLOAD_FOLDER'], 'user_%s' % user_id)
    return send_from_directory(dir_path, filename, as_attachment=True)
